apply plugin: 'io.spring.dependency-management'
apply plugin: 'java'
apply plugin: 'maven-publish'
apply plugin: 'idea'
apply plugin: 'eclipse'

def pluginVersion = '1.1.3'

buildscript {
    ext {
        vXnat = "1.9.0"
    }
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
        mavenLocal()
        maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
        maven { url "https://nrgxnat.jfrog.io/artifactory/libs-release" }
        maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
        mavenCentral()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:1.0.3.RELEASE"
    }
}

group 'org.nrg.xnat'
version pluginVersion

repositories {
    maven { url "https://plugins.gradle.org/m2/" }
    mavenLocal()
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
    maven { url "https://nrgxnat.jfrog.io/artifactory/libs-release" }
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
    mavenCentral()
    maven { url "https://www.dcm4che.org/maven2/" }
    maven { url "https://oss.sonatype.org/content/repositories/releases/" }
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

compileJava {
    options.fork = false
}

configurations {
    all*.exclude group: 'edu.ucar', module: 'netcdf'
    all*.exclude group: 'jakarta-regexp'
    all*.exclude group: 'net.sf.saxon', module: 'Saxon-B'
    all*.exclude group: 'org.apache.geronimo.specs'
    all*.exclude group: 'javax.sql', module: 'jdbc-stdext'
    all*.exclude group: 'javax.transaction', module: 'jta'
    all*.exclude group: 'javax.servlet', module: 'servlet-api'
    // Add implementAndInclude configuration for dependencies to be packaged
    implementation.extendsFrom(implementAndInclude)
}

configurations.testRuntimeClasspath {
    exclude group: 'com.sun.media', module: 'jai_imageio'
}

dependencyManagement.imports {
    mavenBom "org.nrg:parent:${vXnat}"
}

dependencies {
    compileOnly "org.slf4j:slf4j-api"
    compileOnly "log4j:log4j"
    compileOnly 'javax.servlet:javax.servlet-api'
    compileOnly 'com.google.guava:guava:20.0'
    compileOnly 'commons-lang:commons-lang:2.6'
    compileOnly 'com.fasterxml.jackson.core:jackson-core:2.13.4'
    compileOnly 'com.fasterxml.jackson.core:jackson-annotations:2.13.4'
    compileOnly 'com.fasterxml.jackson.core:jackson-databind:2.13.4'
    compileOnly 'org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final'
    compileOnly 'javax.inject:javax.inject:1'
    compileOnly "org.nrg.xnat:web:${vXnat}"
    compileOnly "org.nrg.xnat:xnat-data-models:${vXnat}"
    compileOnly "org.nrg.xdat:core:${vXnat}"
    compileOnly("org.nrg:framework:${vXnat}")
    compileOnly "org.nrg:config:${vXnat}"
    compileOnly "org.springframework:spring-beans"
    compileOnly "org.springframework:spring-context"
    compileOnly "org.springframework:spring-web"
    compileOnly "org.springframework:spring-webmvc"
    compileOnly "io.springfox:springfox-swagger2"
    compileOnly "io.springfox:springfox-swagger-ui"

    // DCM4CHE for DICOMweb support (packaged in plugin)
    implementAndInclude "org.dcm4che:dcm4che-core:5.29.2"
    implementAndInclude "org.dcm4che:dcm4che-json:5.29.2"
    implementAndInclude "org.dcm4che:dcm4che-imageio:5.29.2"
    implementAndInclude "org.dcm4che:dcm4che-image:5.29.2"
    implementAndInclude "org.dcm4che:dcm4che-net:5.29.2"

    // Apache Mime4J for multipart/related parsing (packaged in plugin)
    implementAndInclude 'org.apache.james:apache-mime4j-core:0.8.9'
    implementAndInclude 'org.apache.james:apache-mime4j-dom:0.8.9'

    // Additional dependencies (packaged in plugin)
    implementAndInclude 'commons-io:commons-io:2.11.0'
    implementAndInclude 'org.apache.commons:commons-compress:1.21'
    compileOnly 'commons-fileupload:commons-fileupload:1.4'

    // AnimatedGifEncoder for animated GIF generation (packaged in plugin)
    implementAndInclude 'com.madgag:animated-gif-lib:1.4'

    testImplementation group: 'junit', name: 'junit'
    testImplementation "org.springframework:spring-test"
    testImplementation "org.mockito:mockito-core:4.8.0"
    testImplementation "javax.servlet:javax.servlet-api"
    testImplementation ("org.nrg.xnat:xnat-data-models:${vXnat}") {
        exclude group: 'com.sun.media', module: 'jai_imageio'
    }
    testImplementation ("org.nrg.xdat:core:${vXnat}") {
        exclude group: 'com.sun.media', module: 'jai_imageio'
    }
    testImplementation ("org.nrg.xnat:web:${vXnat}") {
        exclude group: 'com.sun.media', module: 'jai_imageio'
    }
    testImplementation ("org.nrg:framework:${vXnat}") {
        exclude group: 'com.sun.media', module: 'jai_imageio'
    }
    // Test dependencies that need actual implementations
    testImplementation "org.dcm4che:dcm4che-core:5.29.2"
    testImplementation "org.dcm4che:dcm4che-json:5.29.2"
    testImplementation("org.dcm4che:dcm4che-imageio:5.29.2") {
        exclude group: 'com.sun.media', module: 'jai_imageio'
    }
    testImplementation("org.dcm4che:dcm4che-image:5.29.2") {
        exclude group: 'com.sun.media', module: 'jai_imageio'
    }
    testImplementation 'org.apache.james:apache-mime4j-core:0.8.9'
    testImplementation 'org.apache.james:apache-mime4j-dom:0.8.9'
    testImplementation "org.slf4j:slf4j-api"
    testImplementation "org.slf4j:slf4j-simple:1.7.30"
}

jar {
    manifest {
        attributes(
                'Implementation-Title': 'XNAT DICOMweb Proxy Plugin',
                'Implementation-Version': version
        )
    }
}

task xnatPluginJar(type: Jar) {
    zip64 true
    archiveClassifier.set "xpl"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
                'Implementation-Title': 'XNAT DICOMweb Proxy Plugin',
                'Implementation-Version': version
        )
    }
    // Exclude development resources
    exclude "**/resources/**/*-dev**"
    exclude "**/resources/**/*--xx**"
    // Include all implementAndInclude dependencies
    from {
        configurations.implementAndInclude.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
    with jar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
}
